serveFrontend: false
kafka:
  brokers: ["redpanda:19092"]
  schemaRegistry:
    enabled: false
    urls: ["http://redpanda:18081"]
redpanda:
  adminApi:
    enabled: false
    urls: ["http://redpanda:19644"]
connect:
  enabled: false
  clusters:
    - name: local-connect-cluster
      url: http://connect:18083
    - name: local-connect-cluster2
      url: http://connect:18083
server:
  listenPort: 9090
  allowedOrigins: ["http://localhost:3000", "http://localhost:3001"]
  # debug: 
  #   enabled: true
# logger:
  # level: "debug"