serveFrontend: false
kafka:
  brokers: ["redpanda:9092"]
  schemaRegistry:
    enabled: true
    urls: ["http://redpanda:8081"]
redpanda:
  adminApi:
    enabled: true
    urls: ["http://redpanda:9644"]
connect:
  enabled: true
  clusters:
    - name: local-connect-cluster
      url: http://connect:8083
    - name: local-connect-cluster2
      url: http://connect:8083
server:
  listenPort: 9090
  allowedOrigins: ["http://localhost:3000", "http://localhost:3001"]
  # debug: 
  #   enabled: true
logger:
  level: "debug"